BrowseProfiles
wangbertha/convene-app-frontend pull request #40
Opened 2024-11-14 17:46 UTC by dej-code

Completed functionality for the BrowseProfiles section

2024-11-14 17:49 UTC, beefchief-code commented on src/layout/ProfileCard.jsx
> +
check capitalization on profileCard.css - causing build failure

2024-11-14 22:28 UTC, wangbertha requested changes
BrowseProfiles looks great, just need to clear out the extra routing files/code:

- remove LandingPage.jsx, Home.jsx
- remove router variable from App.jsx

2024-11-15 01:59 UTC, dej-code commented on src/layout/ProfileCard.jsx
> +
resolved

2024-11-15 02:00 UTC, dej-code reviewed
resolved

2024-11-15 04:18 UTC, beefchief-code approved these changes
looks good! build is working

2024-11-15 04:18 UTC, wangbertha approved these changes

2024-11-15 04:19 UTC, merged