Homepage
wangbertha/convene-app-frontend pull request #5
Opened 2024-10-31 16:16 UTC by dej-code

I fixed the initial pull request lol

2024-10-31 16:23 UTC, beefchief-code commented on src/App.jsx
> +import LoginPage from './pages/LoginPage';
check import names for login/Auth. files are in /src/components/auth

2024-10-31 16:42 UTC, wangbertha requested changes
Some other general feedback:
- Can you capitalize the names of the React files to match industry norm?
- As a team we decided to use the components/layout folder structure, so some of the file locations would look like this:
   - src/components/users/BrowseProfile.jsx
   - src/components/users/ProfileCard.jsx
   - src/layout/LandingPage.jsx
   - src/layout/Footer.jsx
   - src/layout/NavBar.jsx

I'm not familiar with the swiping animations but I'll trust you on those! Do we want the swiping animation to work from the browser too? (From the phone would be very cool, but I'm not sure how intuitive it would be from the browser)

2024-10-31 16:42 UTC, wangbertha commented on index.html
> +    <link rel="stylesheet" href="/styles/global.css" />
Remove these 2 link tags, since we can import them in the React components

2024-10-31 16:42 UTC, wangbertha commented on src/App.jsx
> +import { BrowserRouter as Router, Routes, Route } from 'react-router-dom';
React updated the BrowserRouter syntax, and our code currently has that provided in router.jsx and the <RouterProvider> tag. You can structure the additional paths you want to add in router.jsx

Feel free to reference the layout structure here!:
https://github.com/beefchief-code/group5.FSU.frontend/tree/main/src/layout

2024-10-31 16:42 UTC, wangbertha commented on src/components/navBar.jsx
> +      <Link to="/">CONVENE</Link>
The <NavLink> tag matches better for this component since it's part of the site navigation

2024-10-31 16:42 UTC, wangbertha commented on src/components/profileCard.jsx
> +  const handleSwipe = (direction) => {
This is above my paygrade at the moment so I'll trust you on this!

2024-11-01 04:13 UTC, castaneda-ed commented
I think that we don't need that function for the browser

2024-11-01 04:14 UTC, castaneda-ed commented
> Some other general feedback:
> - Can you capitalize the names of the React files to match industry norm?
> - As a team we decided to use the components/layout folder structure, so some of the file locations would look like this:
>    - src/components/users/BrowseProfile.jsx
>    - src/components/users/ProfileCard.jsx
>    - src/layout/LandingPage.jsx
>    - src/layout/Footer.jsx
>    - src/layout/NavBar.jsx
> 
> I'm not familiar with the swiping animations but I'll trust you on those! Do we want the swiping animation to work from the browser too? (From the phone would be very cool, but I'm not sure how intuitive it would be from the browser)

I think that we don't need that function for the browser

2024-11-01 22:34 UTC, closed without merging